import 'package:copernican/Models/Planet.dart';

List<Planet> Planets = [
  Planet(
      title: "Mercury",
      shortDesc: "Smallest planet in the solar system.",
      description: "a description of planet earth",
      imageURL: "assets/images/mercury.png",
      modelURL: "assets/models/mercury_3d.glb",
      noOfMoons: "0",
      diameter: "4879 KM",
      mass: "3.30 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Venus",
      shortDesc: "Brightest planet in the solar system.",
      description: "a description of planet earth",
      imageURL: "assets/images/venus.png",
      modelURL: "assets/models/venus_3d.glb",
      noOfMoons: "0",
      diameter: "12,104 KM",
      mass: "48.7 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Earth",
      shortDesc: "A planet with life.",
      description: "a description of planet earth",
      imageURL: "assets/images/earth.png",
      modelURL:
          "C:/Users/Nishith S Suvarna/Desktop/flutter/copernican/assets/models/earth_3d.glb",
      noOfMoons: "1",
      diameter: "12,756	KM",
      mass: "59.7 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Mars",
      shortDesc: "The Red Planet.",
      description: "a description of planet earth",
      imageURL: "assets/images/mars.png",
      modelURL: "assets/models/mars_3d.glb",
      noOfMoons: "2",
      diameter: "6794 KM",
      mass: "6.42 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Jupiter",
      shortDesc: "The largest planet in the solar system.",
      description: "a description of planet earth",
      imageURL: "assets/images/jupiter.png",
      modelURL: "assets/models/jupiter_3d.glb",
      noOfMoons: "95",
      diameter: "142,980 KM",
      mass: "18999.98 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Saturn",
      shortDesc: "The Ringed Planet.",
      description: "a description of planet earth",
      imageURL: "assets/images/saturn.png",
      modelURL: "assets/models/saturn_3d.glb",
      noOfMoons: "146",
      diameter: "120,540 KM",
      mass: "5685 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Uranus",
      shortDesc: "Ice Giant of solar system.",
      description: "a description of planet earth",
      imageURL: "assets/images/uranus.png",
      modelURL: "assets/models/uranus_3d.glb",
      noOfMoons: "27",
      diameter: "51,120 KM",
      mass: "868 x 10\u00B2\u00B3 KG"),
  Planet(
      title: "Neptune",
      shortDesc: "The outermost planet.",
      description: "a description of planet earth",
      imageURL: "assets/images/neptune.png",
      modelURL: "assets/models/neptune_3d.glb",
      noOfMoons: "14",
      diameter: "49,530 KM",
      mass: "1024.1 x 10\u00B2\u00B3 KG"),
];
